[versions]
agp = "8.13.1"
kotlin = "2.0.21"
coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
junit = "4.13.2"
extJunitKtx = "1.3.0"
testRunner = "1.7.0"
testRules = "1.7.0"
espresso = "3.7.0"
uiAutomator = "2.4.0-alpha06"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-junit-ktx = { group = "androidx.test.ext", name = "junit", version.ref = "extJunitKtx" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "testRunner" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "testRules" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espresso" }
androidx-ui-automator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiAutomator" }

[bundles]
android-testing = [
    "junit", "androidx-test-junit-ktx",
    "androidx-test-runner", "androidx-test-rules",
    "androidx-espresso-core", "androidx-espresso-intents",
    "androidx-ui-automator"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
